//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerry Xie.
        /// </summary>
        public static string AuthorInfo_Name {
            get {
                return ResourceManager.GetString("AuthorInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer.
        /// </summary>
        public static string AuthorInfo_Pos {
            get {
                return ResourceManager.GetString("AuthorInfo_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerry Xie&apos;s Blog.
        /// </summary>
        public static string Blog_Title {
            get {
                return ResourceManager.GetString("Blog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me.
        /// </summary>
        public static string ContactMe {
            get {
                return ResourceManager.GetString("ContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two years’ study in IIT, let me touch a lot of genius and top students in different fields. They influent my thought and my perspective to study, from an original passive receiver to now, an enthusiastic self-learner. Also, heavy homework and projects make me study more efficient and more result-oriented  than before..
        /// </summary>
        public static string Education_Desc_1 {
            get {
                return ResourceManager.GetString("Education_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I got my bachelor degree in china. I still remember it was my second semester that the first time I encountered the C language which is so attractive to me. I treated it as the Lego, which I could use to build anything from scratch, I start addicting in programming and science about computer. Four years’ electronic study let me better understand the structure of the computer and gain the ability to program in a lower level like the assembly language which is a great help to me in my future work and study..
        /// </summary>
        public static string Education_Desc_2 {
            get {
                return ResourceManager.GetString("Education_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master of Science in Computer Science    GPA3.75/4.
        /// </summary>
        public static string Education_MajorName_1 {
            get {
                return ResourceManager.GetString("Education_MajorName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor of Electronic Engineering and its Automation   GPA3.75/4.
        /// </summary>
        public static string Education_MajorName_2 {
            get {
                return ResourceManager.GetString("Education_MajorName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Aug 2013 - 15 May 2015.
        /// </summary>
        public static string Education_SchoolDuration_1 {
            get {
                return ResourceManager.GetString("Education_SchoolDuration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 Sep 2008 - 01 June 2012.
        /// </summary>
        public static string Education_SchoolDuration_2 {
            get {
                return ResourceManager.GetString("Education_SchoolDuration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illinois Institute of Technology    .
        /// </summary>
        public static string Education_SchoolName_1 {
            get {
                return ResourceManager.GetString("Education_SchoolName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JiangSu University    .
        /// </summary>
        public static string Education_SchoolName_2 {
            get {
                return ResourceManager.GetString("Education_SchoolName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a place to share my thoughts, my experience and my ideas..
        /// </summary>
        public static string Index_ArticleDescription {
            get {
                return ResourceManager.GetString("Index_ArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography is a way of feeling, of touching, of loving. it remembers little things, long after you have forgotten everything..
        /// </summary>
        public static string Index_GalleryDescription {
            get {
                return ResourceManager.GetString("Index_GalleryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string Index_ViewMore {
            get {
                return ResourceManager.GetString("Index_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer with 3+ years of professional experience in software pattern design and object-oriented programming, and with 1+ year of enterprise project experience in architecture design and code optimization.  Highly familiar with the SQL Server and .NET framework..
        /// </summary>
        public static string Self_Desc {
            get {
                return ResourceManager.GetString("Self_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comment.
        /// </summary>
        public static string ShowComment {
            get {
                return ResourceManager.GetString("ShowComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# .Net Development.
        /// </summary>
        public static string Skills_1 {
            get {
                return ResourceManager.GetString("Skills_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Design.
        /// </summary>
        public static string Skills_2 {
            get {
                return ResourceManager.GetString("Skills_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Development.
        /// </summary>
        public static string Skills_3 {
            get {
                return ResourceManager.GetString("Skills_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a software developer in&lt;a href=&quot;http://healthonellc.com/&quot;&gt; Health One Alliance&lt;/a&gt;, which offers the health service for the whole north Georgia. 60 percentage of my daily job is focusing on implementing an efficient, accurate and secure solution to automatically process all the inbound and outbound EDI Files for company. The rest of my part is to play a key role as a full stack web developer to develop a &lt;a href=&quot;http://getbootstrap.com/&quot;&gt;Bootstrap&lt;/a&gt; based admin portal which including architecture desi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Work_Desc_1 {
            get {
                return ResourceManager.GetString("Work_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year homestay experience living with an IIT chemical professor gives me the chance to join his academic research group. By utilizing the knowledge learn from the advanced algorithm, I successfully   implemented a Complex 3D interpolation algorithm into his alchemical interaction grids, and gained high recommendations by the professor in his LinkedIn page..
        /// </summary>
        public static string Work_Desc_2 {
            get {
                return ResourceManager.GetString("Work_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July 1 2015 - Now.
        /// </summary>
        public static string Work_Duration_1 {
            get {
                return ResourceManager.GetString("Work_Duration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep 1 2014 - May 1 2015.
        /// </summary>
        public static string Work_Duration_2 {
            get {
                return ResourceManager.GetString("Work_Duration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dallas, TX.
        /// </summary>
        public static string Work_PlaceName_1 {
            get {
                return ResourceManager.GetString("Work_PlaceName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicago, IL.
        /// </summary>
        public static string Work_PlaceName_2 {
            get {
                return ResourceManager.GetString("Work_PlaceName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-source Programer.
        /// </summary>
        public static string Work_Title_2 {
            get {
                return ResourceManager.GetString("Work_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work experience.
        /// </summary>
        public static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
    }
}
