//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Here.
        /// </summary>
        public static string AboutMe_PushHere {
            get {
                return ResourceManager.GetString("AboutMe_PushHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yangyang not only possesses technical ability and a passion for programming, but has shown himself to be a good team member. He gets along with everybody else in the research group and has a helpful personality; he has periodically helped weaker programmers with their projects. His English communication skills compare favorably with other international students.I believe that Yangyang will make an excellent addition to a software development organization..
        /// </summary>
        public static string AboutMe_Quotes {
            get {
                return ResourceManager.GetString("AboutMe_Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Minh - Assistant Professor at Illinois Institute of Technology.
        /// </summary>
        public static string AboutMe_Quotes_Author {
            get {
                return ResourceManager.GetString("AboutMe_Quotes_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerry Xie.
        /// </summary>
        public static string AuthorInfo_Name {
            get {
                return ResourceManager.GetString("AuthorInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer.
        /// </summary>
        public static string AuthorInfo_Pos {
            get {
                return ResourceManager.GetString("AuthorInfo_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to top.
        /// </summary>
        public static string BackToTop {
            get {
                return ResourceManager.GetString("BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billboard.
        /// </summary>
        public static string Billboard {
            get {
                return ResourceManager.GetString("Billboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Blog_Title_1 {
            get {
                return ResourceManager.GetString("Blog_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gobi Desert.
        /// </summary>
        public static string Blog_Title_2 {
            get {
                return ResourceManager.GetString("Blog_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brave.
        /// </summary>
        public static string Brave {
            get {
                return ResourceManager.GetString("Brave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Pad.
        /// </summary>
        public static string CodingPad {
            get {
                return ResourceManager.GetString("CodingPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me.
        /// </summary>
        public static string ContactMe {
            get {
                return ResourceManager.GetString("ContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; Personal Website 2015 Designed by jerry.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe Yourself.
        /// </summary>
        public static string DescribeYourself {
            get {
                return ResourceManager.GetString("DescribeYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help you a lot? I need your support !.
        /// </summary>
        public static string DonateRequest {
            get {
                return ResourceManager.GetString("DonateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two years’ study in IIT, let me touch a lot of genius and top students in different fields. They influent my thought and my perspective to study, from an original passive receiver to now, an enthusiastic self-learner. Also, heavy homework and projects make me study more efficient and more result-oriented  than before..
        /// </summary>
        public static string Education_Desc_1 {
            get {
                return ResourceManager.GetString("Education_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I got my bachelor degree in china. I still remember it was my second semester that the first time I encountered the C language which is so attractive to me. I treated it as the Lego, which I could use to build anything from scratch, I start addicting in programming and science about computer. Four years’ electronic study let me better understand the structure of the computer and gain the ability to program in a lower level like the assembly language which is a great help to me in my future work and study..
        /// </summary>
        public static string Education_Desc_2 {
            get {
                return ResourceManager.GetString("Education_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master of Science in Computer Science    GPA3.75/4.
        /// </summary>
        public static string Education_MajorName_1 {
            get {
                return ResourceManager.GetString("Education_MajorName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor of Electronic Engineering and its Automation   GPA3.75/4.
        /// </summary>
        public static string Education_MajorName_2 {
            get {
                return ResourceManager.GetString("Education_MajorName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Aug 2013 - 15 May 2015.
        /// </summary>
        public static string Education_SchoolDuration_1 {
            get {
                return ResourceManager.GetString("Education_SchoolDuration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 Sep 2008 - 01 June 2012.
        /// </summary>
        public static string Education_SchoolDuration_2 {
            get {
                return ResourceManager.GetString("Education_SchoolDuration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illinois Institute of Technology    .
        /// </summary>
        public static string Education_SchoolName_1 {
            get {
                return ResourceManager.GetString("Education_SchoolName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JiangSu University    .
        /// </summary>
        public static string Education_SchoolName_2 {
            get {
                return ResourceManager.GetString("Education_SchoolName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not expose your email address without your permission.
        /// </summary>
        public static string EmailPrivacyPolicy {
            get {
                return ResourceManager.GetString("EmailPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faith.
        /// </summary>
        public static string Faith {
            get {
                return ResourceManager.GetString("Faith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse&apos;s Soulmate.
        /// </summary>
        public static string Horse_soulmate {
            get {
                return ResourceManager.GetString("Horse_soulmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am rich.
        /// </summary>
        public static string I_am_rich {
            get {
                return ResourceManager.GetString("I_am_rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a place to share my thoughts, my experience and my ideas..
        /// </summary>
        public static string Index_ArticleDescription {
            get {
                return ResourceManager.GetString("Index_ArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography is a way of feeling, of touching, of loving. it remembers little things, long after you have forgotten everything..
        /// </summary>
        public static string Index_GalleryDescription {
            get {
                return ResourceManager.GetString("Index_GalleryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string Index_ViewMore {
            get {
                return ResourceManager.GetString("Index_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Comment.
        /// </summary>
        public static string LeaveComment {
            get {
                return ResourceManager.GetString("LeaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular Topics.
        /// </summary>
        public static string MostPopularTopics {
            get {
                return ResourceManager.GetString("MostPopularTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Search.
        /// </summary>
        public static string MusicSearch {
            get {
                return ResourceManager.GetString("MusicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino Webcam ( Need Login).
        /// </summary>
        public static string Pg_ArduinoWebcam {
            get {
                return ResourceManager.GetString("Pg_ArduinoWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Arduino based webcam to monitor the cat at home..
        /// </summary>
        public static string Pg_ArduinoWebcam_Desc {
            get {
                return ResourceManager.GetString("Pg_ArduinoWebcam_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigration Case Tracker.
        /// </summary>
        public static string Pg_CaseTracker {
            get {
                return ResourceManager.GetString("Pg_CaseTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is used to track your case information. Basic idea is querying the offical website periodically. Once your case status got changed, it would pop out an alert immediately.
        /// </summary>
        public static string Pg_CaseTracker_Desc {
            get {
                return ResourceManager.GetString("Pg_CaseTracker_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular JS 2 Designed Web portal for Job Search.
        /// </summary>
        public static string Pg_JobSearch {
            get {
                return ResourceManager.GetString("Pg_JobSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is my Individual project to help people easily find the dream jobs. In the backend, there is a web crawler keep grabing the data from Dice, Indeed and Monster hourly. Search Algorithm is using the full-text search, more accurate and efficient. You don&apos;t need go to each website to apply job repeatly. here is the solution, all in one. Give a vote, if you like it. It is still in development phase.  Welcome for advice. .
        /// </summary>
        public static string Pg_JobSearch_Desc {
            get {
                return ResourceManager.GetString("Pg_JobSearch_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll A Ball.
        /// </summary>
        public static string Pg_RollABall {
            get {
                return ResourceManager.GetString("Pg_RollABall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a simple rolling ball game.
        /// </summary>
        public static string Pg_RollABall_Desc {
            get {
                return ResourceManager.GetString("Pg_RollABall_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a simple top down arcade style shooter..
        /// </summary>
        public static string Pg_SpaceShooter {
            get {
                return ResourceManager.GetString("Pg_SpaceShooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on Unity 3D to build a shooter game..
        /// </summary>
        public static string Pg_SpaceShooter_Desc {
            get {
                return ResourceManager.GetString("Pg_SpaceShooter_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival Shooter.
        /// </summary>
        public static string Pg_SurvivalShooter {
            get {
                return ResourceManager.GetString("Pg_SurvivalShooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an isometric 3D survival shooter game.
        /// </summary>
        public static string Pg_SurvivalShooter_Desc {
            get {
                return ResourceManager.GetString("Pg_SurvivalShooter_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text based Maze game.
        /// </summary>
        public static string Pg_TextBasedMazeGame {
            get {
                return ResourceManager.GetString("Pg_TextBasedMazeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple and interesting terminal style endless maze game..
        /// </summary>
        public static string Pg_TextBasedMazeGame_desc {
            get {
                return ResourceManager.GetString("Pg_TextBasedMazeGame_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures Selected.
        /// </summary>
        public static string PicturesSelected {
            get {
                return ResourceManager.GetString("PicturesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playground.
        /// </summary>
        public static string Playground {
            get {
                return ResourceManager.GetString("Playground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Rate.
        /// </summary>
        public static string PleaseRate {
            get {
                return ResourceManager.GetString("PleaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Time.
        /// </summary>
        public static string PostTime {
            get {
                return ResourceManager.GetString("PostTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Admin portal was implemented to help our inner stuffs to manage the  insurance data  includng Member Management, Group Management, Agency Management, EDI File Monitor and  Report..
        /// </summary>
        public static string Project_AdminPortal_Description {
            get {
                return ResourceManager.GetString("Project_AdminPortal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan 1 2016 - Now.
        /// </summary>
        public static string Project_AdminPortal_Duration {
            get {
                return ResourceManager.GetString("Project_AdminPortal_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Portal.
        /// </summary>
        public static string Project_AdminPortal_Title {
            get {
                return ResourceManager.GetString("Project_AdminPortal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an awsome web project. I used all the most popular technologies  in my project. The front-side framework is the Angular JS 2. The communication between the client side and server side is totally through the RESTful API. The login system is utilzing the OAuth 2.0 --token based authorization. The back-end is using the MVC framework with the Entity framework..
        /// </summary>
        public static string Project_JobSearch_Detail {
            get {
                return ResourceManager.GetString("Project_JobSearch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov 1 2016 - Dec 1 2016.
        /// </summary>
        public static string Project_JobSearch_Duration {
            get {
                return ResourceManager.GetString("Project_JobSearch_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Search.
        /// </summary>
        public static string Project_JobSearch_Title {
            get {
                return ResourceManager.GetString("Project_JobSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project List.
        /// </summary>
        public static string Project_List {
            get {
                return ResourceManager.GetString("Project_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Site.
        /// </summary>
        public static string Project_LiveSite {
            get {
                return ResourceManager.GetString("Project_LiveSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Search was a website let users to quickly find a doctor or hospital in Health One Alliance network. You can either  search  by name, by location or by speciality. As the project leader, I designed the architecture of this website and strictly following the MVC pattern and 3-tier architecture style. For more details, you can click the following button..
        /// </summary>
        public static string Project_ProviderSearch_Detail {
            get {
                return ResourceManager.GetString("Project_ProviderSearch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep 1 2016 - Now.
        /// </summary>
        public static string Project_ProviderSearch_Duration {
            get {
                return ResourceManager.GetString("Project_ProviderSearch_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Search.
        /// </summary>
        public static string Project_ProviderSearch_Title {
            get {
                return ResourceManager.GetString("Project_ProviderSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Detail.
        /// </summary>
        public static string Project_TechnicalDetail {
            get {
                return ResourceManager.GetString("Project_TechnicalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Gallery.
        /// </summary>
        public static string PublicGallery {
            get {
                return ResourceManager.GetString("PublicGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Publish.
        /// </summary>
        public static string RecentPublish {
            get {
                return ResourceManager.GetString("RecentPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer with 3+ years of professional experience in software pattern design and object-oriented programming, and with 1+ year of enterprise project experience in architecture design and code optimization.  Highly familiar with the SQL Server and .NET framework..
        /// </summary>
        public static string Self_Desc {
            get {
                return ResourceManager.GetString("Self_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to my wechat.
        /// </summary>
        public static string ShareToMyWechat {
            get {
                return ResourceManager.GetString("ShareToMyWechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the wechat, click the &quot;discover&quot; in the buttom or &quot;plus&quot; in the right top corner, then using the &quot;Scan QR Code&quot;  to scan the above picture, you would see the content in wechat browser. On the right top corner, click the &quot;three dots&quot; to share this web to my friend cycle.
        /// </summary>
        public static string ShareToMyWechatHelper {
            get {
                return ResourceManager.GetString("ShareToMyWechatHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comment.
        /// </summary>
        public static string ShowComment {
            get {
                return ResourceManager.GetString("ShowComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# .Net Development.
        /// </summary>
        public static string Skills_1 {
            get {
                return ResourceManager.GetString("Skills_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Design.
        /// </summary>
        public static string Skills_2 {
            get {
                return ResourceManager.GetString("Skills_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Development.
        /// </summary>
        public static string Skills_3 {
            get {
                return ResourceManager.GetString("Skills_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Algorithm.
        /// </summary>
        public static string Skills_4 {
            get {
                return ResourceManager.GetString("Skills_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Development.
        /// </summary>
        public static string Skills_5 {
            get {
                return ResourceManager.GetString("Skills_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Showing &lt;span id=&quot;songsNum&quot;&gt;&lt;/span&gt; of &lt;span id=&quot;totalNum&quot;&gt;&lt;/span&gt; related Songs&lt;/p&gt;.
        /// </summary>
        public static string SongListSummary {
            get {
                return ResourceManager.GetString("SongListSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This searching tool is only for &lt;b&gt;study purpose&lt;/b&gt;, Any commerical activities will be &lt;b&gt;prohibited&lt;/b&gt;!.
        /// </summary>
        public static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today‘s Most Popular Pictures.
        /// </summary>
        public static string TodayMostPopularPictures {
            get {
                return ResourceManager.GetString("TodayMostPopularPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Pictures.
        /// </summary>
        public static string TopPictures {
            get {
                return ResourceManager.GetString("TopPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total &lt;span id=&quot;favoriteTotal&quot;&gt;&lt;/span&gt; songs in the list.
        /// </summary>
        public static string TotalSongsInFavorite {
            get {
                return ResourceManager.GetString("TotalSongsInFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Builder.
        /// </summary>
        public static string WebsiteBuilder {
            get {
                return ResourceManager.GetString("WebsiteBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week&apos;s Most Popular Pictures.
        /// </summary>
        public static string WeekMostPopularPictures {
            get {
                return ResourceManager.GetString("WeekMostPopularPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a software developer in&lt;a href=&quot;http://healthonellc.com/&quot;&gt; Health One Alliance&lt;/a&gt;, which offers the health service for the whole north Georgia. 60 percentage of my daily job is focusing on implementing an efficient, accurate and secure solution to automatically process all the inbound and outbound EDI Files for company. The rest of my part is to play a key role as a full stack web developer to develop a &lt;a href=&quot;http://getbootstrap.com/&quot;&gt;Bootstrap&lt;/a&gt; based admin portal which including architecture desi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Work_Desc_1 {
            get {
                return ResourceManager.GetString("Work_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year homestay experience living with an IIT chemical professor gives me the chance to join his academic research group. By utilizing the knowledge learn from the advanced algorithm, I successfully   implemented a Complex 3D interpolation algorithm into his alchemical interaction grids, and gained high recommendations by the professor in his LinkedIn page..
        /// </summary>
        public static string Work_Desc_2 {
            get {
                return ResourceManager.GetString("Work_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July 1 2015 - Now.
        /// </summary>
        public static string Work_Duration_1 {
            get {
                return ResourceManager.GetString("Work_Duration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep 1 2014 - May 1 2015.
        /// </summary>
        public static string Work_Duration_2 {
            get {
                return ResourceManager.GetString("Work_Duration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dallas, TX.
        /// </summary>
        public static string Work_PlaceName_1 {
            get {
                return ResourceManager.GetString("Work_PlaceName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicago, IL.
        /// </summary>
        public static string Work_PlaceName_2 {
            get {
                return ResourceManager.GetString("Work_PlaceName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-source Programer.
        /// </summary>
        public static string Work_Title_2 {
            get {
                return ResourceManager.GetString("Work_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work experience.
        /// </summary>
        public static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You jump I jump.
        /// </summary>
        public static string YouJumpIJump {
            get {
                return ResourceManager.GetString("YouJumpIJump", resourceCulture);
            }
        }
    }
}
